<a href="https://colab.research.google.com/github/priyanka36/MLProblems/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import sys

Why Numpy ? 
- Numpy is a multidimensional array library
- Higher scientific calculations require numpy 
- Stores all sorts of data in one-dimensional array two dimensional arrays etc

Why use NUmpy over lists?
-  Lists are very slow as compared to Numpy

But why are they slow ?
- Our computers represents numbers as a binary coded representation value
- 5 -> 00000101

Numpy this 5 is represented as Int32 representation : 00000000 00000000 00000000 00000101.Total memory space of 4 bytes 

Lists is for built in int type for python.The built in int type consists of the four representations:

Size : 4 bytes 
Reference Count:how many times the integer has been pointed at.(Represented as 8  bytes)
Object Type:Represented as 8  bytes
Object Value : Represented as 8  bytes

So the reason why Numpy is faster then lists are:
- Faster to read less bytes of memory 
- No typechecking in  Numpy
- Numpy uses contiguous memory
- Lists blocks are not contiguous.This causes the list pointers to search for and bounce around the different available locations 
- But why is contiguous memory easy to search for?
- Our computer uses SIMD Vector Processing(Single Instruction Mutliple Data)
- Effective Cache Utilization


How are lists different from Numpy ?
Lists 
-Insertion 
-Deletion
-
a= [1,3,5]
b = [1,2,3]
a*b = Error
Numpy 
- Single element wise computations can be performed 
a*b = [1,6,15]

Application of Numpy?
- (Matlab Replacement)(mathematics with numpy)
- Plotting(Matplotlib)(Plotting of many application)
- Backend(Pandas,Connect4,Digital Photography)(
- Machine Learning





In [ ]:
 a = np.array([1,2,3])
 print(a)

[1 2 3]


In [ ]:
b = np.array([[9,8,7],[6,5,4]])
print(b)

[[9 8 7]
 [6 5 4]]


In [ ]:
#get the dimensions
a.ndim
b.ndim

2

In [ ]:
#get shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# get type
print(a.dtype)
print(b.dtype)

int64
int64


In [ ]:
# get size
print(a.itemsize )
print(b.itemsize)

8
8


In [ ]:
print(a.nbytes )
print(b.nbytes)

24
48


# Accessing Changing specific elements,rows,columns etc


In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
a[1,5]

13

In [ ]:
# get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#get a specific column
a[:,1]

array([2, 9])

In [ ]:
# getting a little more 
a[0,1:-2]

array([2, 3, 4, 5])

In [ ]:
a[:,2]

array([ 3, 10])

In [ ]:
# 3-d example
b= np.array([[[1,2],[3,4],[5,6]]])

In [ ]:
print(b)

[[[1 2]
  [3 4]
  [5 6]]]


In [ ]:
b[:,2,0]

array([5])

In [ ]:
#All o's 
np.zeros()